### ISSUE TITLE
Data Request as per GDPR

### ISSUE THREAD

**Issue by ghost** [sticks-stuff/highlight-RMS-supporters#13]
To Whom It May Concern:
I am requesting you, as the data controller of the dataset `styles.css` contained in your repository, to confirm whether it is processing any personal data about me, a German citizen.
If so, please provide me with all the required information stipulated in Article 15 of the EU General Data Protection Regulation (GDPR), including:
a copy of

-  my personal data;
- the purposes of the processing;
- the categories of personal data concerned;
- the recipients you disclose my personal data to and the safeguards you provide;
- the retention period for storing my personal data or the criteria used for determining this period;
- information about the source of my personal data; and;
- the existence of automated decision-making (including profiling), and if so:
  - the logic involved in the decision-making process;
  - the significance and the envisaged consequences for me;
  - the steps you have taken to prevent errors, bias and discrimination; and
  - explain how I can express my point of view and challenge a decision.

This request relates to any processing of my personal data by you, including any processors processing personal data on behalf of you. I look forward to receiving a response within one month of the receipt of my request.
Sincerely, GitGangGuy

**Comment by sticks-stuff** [comment]
All the code and data is open source so you can look at it yourself!

**Comment by ghost** [comment]
@sticks-stuff I do not know where you have stored my data, with whom you have shared it and how to understand the computer programming code.  
Free Software projects are obligated to follow the GDPR as well. I wish you to continue enacting on my request.
The GDPR mandates my personal data takeout is "concise, transparent, intelligible and easily accessible; written in clear and plain language, particularly if addressed to a child."

**Comment by ghost** [comment]
The source code itself does not disclose data use in detail as by requirement of the GDPR. I would also like you to remove my personal data from the `names.json` file as I as a Polish citizen didn't consent to it's processing by you, the dataset controller.
I look forward to my request being processed within three months, if the request isn't processed I will continue with legal action.
Sincerely, Bronzu.

**Comment by ghost** [comment]
@Bronzu Can you please open a seperate issue to keep this organized?

**Comment by ghost** [comment]
Yes, I will.
