### ISSUE TITLE
Make this repo opt-in instead of opt-out

### ISSUE THREAD

**Issue by xerydian** [sticks-stuff/highlight-RMS-supporters#18]
As you can see some people are rightfully requesting opting out from this repo.
Just like signing the letters was opt-in, being in this repo should be opt-in as well.

Please remove all people you assumed consent from, and only put people who explicitly sign up to be here.

**Comment by shenlebantongying** [comment]
In case it actually become opt-in:

I officially grant the repo owner my permission to keep my info in below lines here forever.

https://github.com/sticks-stuff/highlight-RMS-supporters/blob/c3415447f3c238a5d8b4b191bc2e15f2ec1718d0/names.json#L1979-L1980

**Comment by yagehu** [comment]
How do I opt out? Is this repo promoting harassment of people who support RMS?

**Comment by xerydian** [comment]
People are supposed to opt out by giving in to their (stick) blackmail and remove their (people) signature from the rms-support-letter
https://github.com/sticks-stuff/highlight-RMS-supporters/issues/3#issuecomment-808959506

**Comment by ycpei** [comment]
> In case it actually become opt-in:
> 
> I officially grant the repo owner my permission to keep my info in below lines here forever.
> 
> https://github.com/sticks-stuff/highlight-RMS-supporters/blob/c3415447f3c238a5d8b4b191bc2e15f2ec1718d0/names.json#L1979-L1980

@sticks-stuff Please add mine too and only remove me when you have removed everyone who has not given you consent.

**Comment by ghost** [comment]
Check out my PR #31

**Comment by ghost** [comment]
Even before completely deleting this repository - as it is purposeless and only discriminatory - please remove my name and any links connected to any of my profiles, websites or emails. I do not consent to this. Thank you.
