### ISSUE TITLE
This repository violates the GDPR in Europe

### ISSUE THREAD

**Issue by cavallium** [sticks-stuff/highlight-RMS-supporters#34]
Article 4(11) of the General Data Protection Regulation (EU) 2016/679 (GDPR) requires consent to be opt-in:

"Any freely given, specific, informed and unambiguous indication of his or her wishes by which the data subject, either by a statement or by a clear affirmative action, signifies agreement to personal data relating to them being processed; [...] Silence, pre-ticked boxes or inactivity should therefore not constitute consent."

If the repository will not comply with the above mentioned law I will have to take legal action.

**Comment by pac85** [comment]
I ask for my account details to be removed from this list.

**Comment by adamantinum** [comment]
I ask for my account details to be removed from this list too.

**Comment by andrew-ld** [comment]
I ask for my account details to be removed from this list.

**Comment by MarcoBuster** [comment]
I ask for my account details to be removed from this list.
