### ISSUE TITLE
Feature request: Put filename as an argument

### ISSUE THREAD

**Issue by Technoturnovers** [sticks-stuff/highlight-RMS-supporters#38]
I think this would be a useful quality of life improvement.

**Comment by sticks-stuff** [comment]
I'm confused what you're asking. Are you asking for a command line argument to point to a JSON file you want to generate a stylesheet for?

**Comment by Technoturnovers** [comment]
yeah

**Comment by sticks-stuff** [comment]
Probably out of the scope of this project sorry
