### ISSUE TITLE
False positives due to matching too widely

### ISSUE THREAD

**Issue by passcod** [sticks-stuff/highlight-RMS-supporters#4]
`a[href*="foo"]` will match both `foo` and `foobar` and `barfoo`, even if only `foo` was intended to be matched.

**Comment by sticks-stuff** [comment]
You're absolutely correct however I couldn't think of a better way to do it (I'm not an actual programmer) and still allow matching of URLs like https://github.com/TEAM/REPO/commits?author=AUTHOR

Anyone who's an actual developer and knows a good solution to this, please tell me or open a PR :)

**Comment by workingjubilee** [comment]
I do not believe there is any terribly *clean* solution with just CSS.
You can choose the suffix `foo` instead via `$=foo` but that still matches `barfoo`.
You can somewhat tediously enumerate, e.g.
- `$="/foo"`
- `*="/foo/"`
- `$="=foo"`

I should note that user links on most sites are internal links and so follow the pattern of `/foo` exactly, and a suffix match would hit such an example even if it was part of a full URL, so using `$="/foo"` would be a low-effort way to accept a few false negatives but eliminate the vast majority of false positives. Using `i` (e.g. `a[href$="/foo" i]` would widen it to not depend on site-specific conventions around capitalization. Anything more complex would be easier to handle using JS.

**Comment by passcod** [comment]
This is just on github, so matching `[href^="https://github.com/username"]` is probably fine?

**Comment by passcod** [comment]
Or rather, just about github usernames. (Regardless of where they appear.)

**Comment by sticks-stuff** [comment]
It's meant to work on sites other than GitHub (if the signed provided a link other than their GitHub)

**Comment by passcod** [comment]
Hmm, okay, but in that case the generated stylesheet should have the URL, not just the github username part (not just for this issue, but also to avoid conflating someone's username on here with someone else's username on another site).

**Comment by Skazzy3** [comment]
"I'm not an actual programmer"
Understatement of the year

**Comment by reinaldoacosta** [comment]
"Anyone who's an actual developer and knows", someone who was an actual developer would support stallman, troon.
YWNBAW.

**Comment by RosettaHS** [comment]
**>I'm not an actual programmer**
Wanna know how we know?

**Comment by sticks-stuff** [comment]
In recent commits I've updated this to only scope on GitHub users as I realized that it was getting out of hand pretty quickly lol
