### ISSUE TITLE
Please think about us

### ISSUE THREAD

**Issue by PVNFU-28** [sticks-stuff/highlight-RMS-supporters#41]
As someone of jewish descent I feel really uncomfortable being on this list, it literally triggered memories of how they used to target us, and by us I mean close family not too long ago, me and many others of the community would appreciate if you left us out of this. Let us relax for a second.
I hope you understand.

**Comment by smug-dev** [comment]
who asked kid 🤣🤣🤣

**Comment by PVNFU-28** [comment]
There it is, the antisemitism and degradation.

**Comment by T1mL3arn** [comment]
@PVNFU-28 you can report this repo if it feels discriminating to you:

- go to this repo owner's page ( https://github.com/sticks-stuff )
- click `...` button (it is near `Follow` button)
- click `Block or report user` -> `Report abuse`
- select the reason (`harassing content` is the obvious one, but you can select `other` also)
- write in the textfield below what do you want to report ( https://github.com/sticks-stuff/highlight-RMS-supporters ) and why.
- click `Send request`

**Comment by robbyoconnor** [comment]
@T1mL3arn they're going to laugh at you. If you don't like it, take your name off of the letter. Unless you have been around for the past few decades, you're too damn young. If you have never met RMS, pipe down, your opinion doesn't matter.
