### ISSUE TITLE
Ableist language in the source code

### ISSUE THREAD

**Issue by cynical-incendiary** [sticks-stuff/highlight-RMS-supporters#42]
Hi, could you please change "sanity check" to something else; my mentally ill brother doesn't seem to be very comfortable with that, and he's been crying all night. Thx. 

https://github.com/sticks-stuff/highlight-RMS-supporters/blob/1f15d74e5abc8987f88e857e6a4ee18bb2d6a0c8/generate-styles.js#L12
https://github.com/sticks-stuff/highlight-RMS-supporters/blob/1f15d74e5abc8987f88e857e6a4ee18bb2d6a0c8/generate-styles.js#L19

**Comment by ghost** [comment]
LOL
