### ISSUE TITLE
Unable to load the css file due to a cors error

### ISSUE THREAD

**Issue by dvtkrlbs** [sticks-stuff/highlight-RMS-supporters#46]
As the title says the script does not get loaded and i get a cors error. 
<img width="1680" alt="Screen Shot 2021-03-31 at 12 51 31 AM" src="https://user-images.githubusercontent.com/24792168/113061765-3d66ef00-91bb-11eb-8759-1417f62bcf9e.png">

**Comment by shenlebantongying** [comment]
Sadge, this script is sock.
![image](https://user-images.githubusercontent.com/20123683/113062149-4cc94680-9181-11eb-9f7c-5a1e2de5104e.png)

**Comment by midnya** [comment]
There should be an option to disable CSPin your UserScript loader.
For example, with TamperMonkey:

- In the "Settings" tab, set the config mode value to "Advanced" 
![image](https://user-images.githubusercontent.com/30862392/113078273-0d2b4a80-91d3-11eb-85e7-198dcc7fc170.png)

- In the Security section, set the value to "Disable entirely"
![image](https://user-images.githubusercontent.com/30862392/113078341-2fbd6380-91d3-11eb-9f80-f6827dc03591.png)

It should then work.
I'll look for a better solution tomorrow.

**Comment by sticks-stuff** [comment]
Should be fixed as of #56
