### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by SuperFola** [sticks-stuff/highlight-RMS-supporters#53]
I'm not going to say this project is bad or not, I don't want to discuss about that here, but as a developper I must point you that this script will just bloat any computer it will be on. CSS parsers such as the one of Mozzila, when you're using this script, will consume hundreds of megs of memory (just to see I tried to install the CSS, more than a gig later I gave up and deleted it, having proven my point).

CSS user styles *and* JS user scripts are really, really, really bad (unless you want to burn computers).

Alas I don't have suggestions to improve that, but you should definitly address that.

**Comment by midnya** [comment]
No such memory consumption. Try better.

**Comment by shenlebantongying** [comment]
The solution posed by me only consume 1 kb of memory.

**Comment by SuperFola** [comment]
> 
> 
> No such memory consumption. Try better.

Well, my extension "Stylish" does indeed consume more than a gig of RAM only to load the CSS. I'm a hater of user scripts, because using external JS code in your navigator in *every* page is an abomination to me, and of all the JS runtimes I tried, they all consume a lot of RAM to do just useless things.

**Comment by midnya** [comment]
@sticks-stuff close, please. Stylus works like a charm. This repository doesn't have to adapt to badly developed extensions, or badly configured web browsers.

**Comment by Alexhuszagh** [comment]
> 
> 
> > No such memory consumption. Try better.
> 
> Well, my extension "Stylish" does indeed consume more than a gig of RAM only to load the CSS. I'm a hater of user scripts, because using external JS code in your navigator in _every_ page is an abomination to me, and of all the JS runtimes I tried, they all consume a lot of RAM to do just useless things.

Just an FYI: Stylish was widely reported to be spyware and isn't supposed to be used anymore. It was returned to the app store after a user agreement that you allow them to [monitor ](https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/)your entire browsing history and data on every webpage. Also, there's no need to use Stylish here: memory usage isn't significant with this userscript. If you want an open-source alternative that doesn't steal all your data, use [Stylus](https://add0n.com/stylus.html).

**Comment by SuperFola** [comment]
> 
> 
> > > No such memory consumption. Try better.
> > 
> > 
> > Well, my extension "Stylish" does indeed consume more than a gig of RAM only to load the CSS. I'm a hater of user scripts, because using external JS code in your navigator in _every_ page is an abomination to me, and of all the JS runtimes I tried, they all consume a lot of RAM to do just useless things.
> 
> Just an FYI: Stylish was widely reported to be spyware and isn't supposed to be used anymore. It was returned to the app store after a user agreement that you allow them to [monitor ](https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/)your entire browsing history and data on every webpage. Also, there's no need to use Stylish here: memory usage isn't significant with this userscript. If you want an open-source alternative that doesn't steal all your data, use [Stylus](https://add0n.com/stylus.html).

Well now that's a kind reply I understand, instead of being spite to the face because I report something some people do not value because they think they are over everyone else. Thanks for your reply, I didn't know that about Stylish.

**Comment by gretchenfrage** [comment]
A possible solution could be based on replacing the pure-CSS approach with some client-side JavaScript which listens for newly loaded elements (?) and checks them against a database. When I say "database", something simple could probably work, such as file containing a list of usernames.

**Comment by sticks-stuff** [comment]
Fixed as of #56
