### ISSUE TITLE
Please just don't do that.

### ISSUE THREAD

**Issue by ertodebana** [sticks-stuff/highlight-RMS-supporters#57]
They signed the letter and that is it. You don't have to highlight their names without their consent. This is inappropriate.

**Comment by istem** [comment]
Yes. This like as "Yellow badges" from nazis.

**Comment by ghost** [comment]
@istem , @EmperorBale report the repository to Github (as I did), if you haven't already. This is very near to the border of human rights.
We could instead just discuss things as people... : (

**Comment by ghost** [comment]
Get the law involved. This repository is in violation of the GDPR.

**Comment by ghost** [comment]
@sticks-stuff you DO realize this won't get you and your pronouns anywhere, don't you? :)

**Comment by ghost** [comment]
Pronouns serve a great deal to human rights. Introducing them to the language is nothing more than natural and helpful. 
Free software is about human rights.
@JackRedstonia Do not be derogatory, they are people like us. Asking is one thing, stepping on someones feet is another.
Also, we all know what is going on, let's not steer it any other direction.
@sticks-stuff please try not to be fooled by false news and read on a bit more.

**Comment by ghost** [comment]
Let's not get to the point where you start defending identity politics.

**Comment by ghost** [comment]
@JackRedstonia be civil, be responsible, be humane, be respectful. Let's keep this on track. I believe you can.
We are putting out the fire, not fueling the flames. Are you?
Arguments are to come to a solution, not to get at each other.
Let's count to three. A one, a two, freeee. (lol)
Feel free to argue with me somewhere else if you need to vent a bit, see my profile.
