### ISSUE TITLE
Please add my name

### ISSUE THREAD

**Issue by ycpei** [sticks-stuff/highlight-RMS-supporters#59]
Please don't discriminate against me just because I signed the support letter with a non-Github link.

Please fix, thank you.

Name: Yuchen Pei
Github: https://github.com/ycpei

**Comment by ycpei** [comment]
I find it offensive that people like me are worth `null` in your code:

```
    if (!(link.host == 'github.com' || link.host == 'www.github.com')) {
        // link is not github.com
        return null;
    }
```

Please fix.

**Comment by sticks-stuff** [comment]
At this time the script cannot be manually added to. Sorry!
