### ISSUE TITLE
processing of possibly personal information without consent

### ISSUE THREAD

**Issue by Jan200101** [sticks-stuff/highlight-RMS-supporters#6]
The way the repo currently works it depends on a bot to fetch the information and save it into the repository
this not only contains github users but also email and personal websites of people that many have not given consent to publishing here

personally I think its better to do it like this shell script https://gist.github.com/kyhwana/73161a50d1b5019b18e3965b55a1a192
and fetch the list dynamically

**Comment by lionirdeadman** [comment]
GitHub already shows a list of the users as contributors of the repository. This repo isn't doing anything different from my POV.

**Comment by Jan200101** [comment]
As it stands GitHub has explicit permission to list contributors on a project which has been given when you signed up to the service
I have not signed up to this repository and neither was I informated about the processing

not to mention that the list does not contain the list of contibutors but the information provided onto the letter

**Comment by Jan200101** [comment]
As it stands this seems to be in violation of the GDPR too mainly being
```
There is a need for transparency regarding the gathering and use of data in order to allow EU citizens to exercise their right to the protection of personal data.
Therefore, the General Data Protection Regulation (GDPR) gives individuals a right to be informed about the collection and use of their personal data, which leads to a variety of information obligations by the controller.
```
https://gdpr-info.eu/issues/right-to-be-informed/

```
In most cases, commissioned data processing proceeds based on a contract. Art. 28(3) GDPR sets forth its minimum requirements.
The contract must contain, among other things, what type of personal data will be processed, as well as the object and purpose of the processing. In addition, there are further obligations for the processor.
```
https://gdpr-info.eu/issues/processing/

The tooling also seems to be not setup to remove people from the list so the right to be forgotten is also violated

Another repository in violation is https://github.com/travisbrown/octocrabby but I cannot open an issue there

**Comment by sticks-stuff** [comment]
Hi, those who want to remove their names from this repo may remove their names from https://github.com/rms-support-letter/rms-support-letter.github.io and the bot will also remove your name from here :)

**Comment by Jan200101** [comment]
I find it sad that you take a GDPR violation like this so lightly
