### ISSUE TITLE
Why is this script even here?

### ISSUE THREAD

**Issue by steveeq1** [sticks-stuff/highlight-RMS-supporters#61]
What is the purpose of highlighting Stallman supporters? I don't get it.

**Comment by ErikPrantare** [comment]
Same reason jews were made to wear yellow badges.
https://en.wikipedia.org/wiki/Yellow_badge

**Comment by steveeq1** [comment]
Don't you find it freaky that internet mobs are starting to do this? For merely having a different opinion about Stallman?

**Comment by ErikPrantare** [comment]
It's kinda cringe yeah. Best you can do is simply report it and move on with your life.
sticks-stuff -> click the ... under the pfp -> Block or report user

**Comment by steveeq1** [comment]
Ok, I'll report him. and I'll get my friends to report him as well. sticks-stuff is doing something that will lead to "mob harassment".

**Comment by ErikPrantare** [comment]
Sounds good. Just don't give these people any brain space. They thrive off of your fear.
