### ISSUE TITLE
Database removal

### ISSUE THREAD

**Issue by sowa705** [sticks-stuff/highlight-RMS-supporters#7]
It seems that your database contains my name and github page, i did not consent to this information being collected by you. please remove me from your database.

**Comment by purplesyringa** [comment]
Hello, I second this. I have only allowed GitHub to process my data upon agreeing with their Terms of Service, and allowed rms-support-letter to use my name and ID when I made a PR. Using my data without my contest violates GDPR. Please kindly remove my name and ID from this repository.

**Comment by ghost** [comment]
I don't consent to my information being in this either. Please remove it

**Comment by shenlebantongying** [comment]
I officially grant the repo owner my permission to keep my info in below lines here forever.

https://github.com/sticks-stuff/highlight-RMS-supporters/blob/c3415447f3c238a5d8b4b191bc2e15f2ec1718d0/names.json#L1979-L1980

**Comment by nukeop** [comment]
I grant the owner of this repo the right to keep my username in that huge json file just so I can laugh at the sheer ineptitude of this solution.

**Comment by sticks-stuff** [comment]
Hi, those who want to remove their names from this repo may remove their names from https://github.com/rms-support-letter/rms-support-letter.github.io and the bot will also remove your name from here :)

**Comment by purplesyringa** [comment]
Hello, unfortunately I will have to contact GitHub moderators and ask them to get your repository hidden because this is clearly a violation of my rights. I do not want to proceed further and take legal action, so I kindly ask you to remove me and others on this issue again.

**Comment by Jan200101** [comment]
as it stands I have reported this and https://github.com/travisbrown/octocrabby to Github Support as GDPR violations
![image](https://user-images.githubusercontent.com/15076013/112768341-fa224a00-901b-11eb-92e1-e8bb005e543b.png)

**Comment by eddyb** [comment]
> Hello, I second this. I have only allowed GitHub to process my data upon agreeing with their Terms of Service, and allowed rms-support-letter to use my name and ID when I made a PR. Using my data without my contest violates GDPR. Please kindly remove my name and ID from this repository.

These "Terms of Service"? https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users

**Comment by purplesyringa** [comment]
Yes. Quoting from your link:

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

This states that everyone may see my personal data and reproduce it on GitHub via forking and such, but you cannot anyhow use it or process it apart from using GitHub interface, as done by this script.

**Comment by ghost** [comment]
I've also reported the repository.

> as it stands I have reported this and https://github.com/travisbrown/octocrabby to Github Support as GDPR violations
> ![image](https://user-images.githubusercontent.com/15076013/112768341-fa224a00-901b-11eb-92e1-e8bb005e543b.png)

**Comment by completesomething** [comment]
I invite the project maintainer to think about how processing personal information without consent correlates with the principles of free software.

**Comment by nicoonoclaste** [comment]
People invoking the [GDPR] in here might want to read Article 9; specifically, paragraph 2 defines special categories exempt from GDPR obligations, including:

> (e) processing relates to personal data which are manifestly made public by the data subject;

In that light, @sticks-stuff's [proposed solution] is absolutely correct:
- only people who “manifestly made public” their support of RMS are included;
- withdrawing that support from the public record causes prompt removal from this repo;  
  (not sure that's a requirement per GDPR, but it's still good practice)
- their rights to rectification (Art. 16) and erasure (Art. 17) are automatically enforced.

Note: I am *not* a lawyer, let alone your lawyer, whoever you are.

[GDPR]: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02016R0679-20160504
[proposed solution]: https://github.com/sticks-stuff/highlight-RMS-supporters/issues/7#issuecomment-808959295

**Comment by sowa705** [comment]
Im not sure if you are correct, the article 9 "manifestly made public" part is vague and was not tested in court (also im not sure if this collection is legal as GPLv3 - rms-support-letter license only handles software, not personal data). Also my right to erasure is not enforced as @sticks-stuff did not comply with my request to remove my data from this repository.

**Comment by cristeigabriela** [comment]
LOL @ this. So cucked

**Comment by Jan200101** [comment]
> People invoking the [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02016R0679-20160504) in here might want to read Article 9; specifically, paragraph 2 defines special categories exempt from GDPR obligations, including:
> 
> > (e) processing relates to personal data which are manifestly made public by the data subject;

Paragraph 2. clearly sates
> 2.  Paragraph 1 shall not apply if one of the following applies:

which in this case makes the definition of personal data is rather muddy and implied to be what is specified in Paragraph 1

> 1.  Processing of personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation shall be prohibited.

which to, break it up, lists the following:
- racial and ethnic origin
- political opinion
- religious or philosophical beliefs
- trade unnion membership
- genetic and biometric data for the purpose of identification
- data concerning health
- data concerning a person's sex life
- sexual orientation

> Hi, those who want to remove their names from this repo may remove their names from https://github.com/rms-support-letter/rms-support-letter.github.io and the bot will also remove your name from here :)

This is a gross response considering the data processed in this repository
I suggest the source code to be changed up to gather the data on the fly instead of having to process and store it
like https://gist.github.com/kyhwana/73161a50d1b5019b18e3965b55a1a192
If desired I am willing to help work on that @sticks-stuff
